title: Team-Dominus
description: Team-Dominus's website
baseurl: ""
url: https://Team-Dominus.github.io/Team-Dominus/

theme: cvless

# site settings
taglong: Jekyll theme for a beautiful online CV
tagshort: Jekyll theme
cv: true

# author settings
author:
  name: Team-Dominus
  email: teamdominus0601@gmail.com
photo: assets/files/Logow.BG.png
joblines:
  - University of Jekyll
  - Department of Themes
  - 123 Main St, Anytown, USA
address: Foobar Hall 1.23
phone: +1 234 567 890

# profile links
profile:
  facebook: https://www.facebook.com/username
  x: https://x.com/username
  mastodon: https://mastodon.social/@username
  bluesky: https://bsky.app/profile/username.bsky.social
  instagram: https://www.instagram.com/dominus0601/
  linkedin: https://www.linkedin.com/in/username
  xing: https://www.xing.com/profile/username
  stackoverflow: https://stackoverflow.com/users/0000000/username
  medium: https://medium.com/@username
  github: https://github.com/Team-Dominus

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
