title: Team-Dominus
description: Team-Dominus's website
baseurl: ""
url: https://Team-Dominus.github.io/

#theme: cvless

# site settings
taglong: Jekyll theme for a beautiful online CV
tagshort: Jekyll theme
cv: true

# author settings
author:
  name: Team-Dominus
  email: teamdominus0601@gmail.com
photo: assets/files/Logo.png
joblines:
  - University of Jekyll
  - Department of Themes
  - 123 Main St, Anytown, USA
address: Foobar Hall 1.23
phone: +1 234 567 890

# profile links
profile:
  x: https://x.com/username
  instagram: https://www.instagram.com/dominus0601/
  github: https://github.com/Team-Dominus

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
